name: default

train:
  numEpochs: 100
  numBatches: 100
  batchSize: 4

  width: 64
  height: 64
  channels: 3
  scale: 2
  views: 2
  
  model:
    width: 16
    blocks: 8

  path: 
    input: "./input"
    target: "./target"

  optim:
    type: Adam
    lr: 0.001
    betas: [0.9, 0.9]

  sched:
    type: MultiStepLR
    gamma: 0.1
    milestones: [50, 80, 120]

