name: default

train:
  numEpochs: 100
  numBatches: 100
  batchSize: 1

  width: 64
  height: 64
  channels: 3
  scale: 2
  views: 2
  
  model:
    width: 48
    blocks: 12

  datapath: "/home/limitz/projects/NAFNet/datasets/StereoSR/test/KITTI2012/hr"

  optim:
    type: Adam
    lr: 0.003
    betas: [0.9, 0.999]

  sched:
    type: MultiStepLR
    gamma: 0.1
    milestones: [20, 60, 90]

