name: default

train:
  numEpochs: 120
  numBatches: 32
  batchSize: 16 

  width: 64 
  height: 64 
  channels: 3
  scale: 2
  views: 2
  
  model:
    width: 48
    blocks: 12

  datapath: 
    train: "/home/wipkat/data/ssr_train"
    validate: "/home/wipkat/data/ssr_val"

  optim:
    type: Adam
    lr: 0.003
    betas: [0.9, 0.999]

  sched:
    type: MultiStepLR
    gamma: 0.2
    milestones: [30, 60, 90]

infer:
  width: 1024
  height: 512
  in_channels: 3
  out_channels: 3
  
  checkpoint: "./checkpoints/default.100.pth"
  datapath: "/home/wipkat/data/ssr_infer/input"
  outpath: "/home/wipkat/data/ssr_output"

