name: pipnet5

train:
  numEpochs: 400
  numBatches: 16 
  batchSize: 16

  width: 128
  height: 128
  in_channels: 1
  out_channels: 12 
  
  datapath: "/home/wipkat/data/pip_train"

  augment:
    rotate: True
    scale: True

  optim:
    type: Adam
    lr: 0.003
    betas: [0.9, 0.999]

  sched:
    type: MultiStepLR
    gamma: 0.3
    milestones: [20, 50, 80, 120, 180, 240, 320]

validate:
  batchSize: 4
  numBatches: 4
  width: 256
  height: 256
  
  in_channels: 1
  out_channels: 12 

  augment:
    rotate: False
    scale: True
  datapath: "/home/wipkat/data/pip_val"

  infer:
    width: 1920
    height: 1440
    in_channels: 1
    out_channels: 12

    datapath: "/home/wipkat/data/pip_infer"
    output: "/home/wipkat/data/pip_output"
