name: pipnet3

train:
  numEpochs: 200
  numBatches: 32
  batchSize: 16

  width: 128 
  height: 128
  in_channels: 1
  out_channels: 12 
  
  datapath: 
    train: "/home/wipkat/data/pip_train"
    validate: "/home/wipkat/data/pip_val"

  optim:
    type: Adam
    lr: 0.003
    betas: [0.9, 0.999]

  sched:
    type: MultiStepLR
    gamma: 0.1
    milestones: [40, 100, 160]

