name: default

train:
  numEpochs: 120
  numBatches: 64
  batchSize: 4

  width: 64 
  height: 64 
  in_channels: 1
  out_channels: 16 
  
  datapath: 
    train: "/home/wipkat/data/pip_train"
    validate: "/home/wipkat/data/pip_val"

  optim:
    type: Adam
    lr: 0.003
    betas: [0.9, 0.999]

  sched:
    type: MultiStepLR
    gamma: 0.1
    milestones: [30, 60, 90]

