name: pipnet3

train:
  numEpochs: 200
  numBatches: 32
  batchSize: 16

  width: 128 
  height: 128
  in_channels: 1
  out_channels: 12 
  
  datapath: "/home/wipkat/data/pip_train"

  augment:
    rotate: True
    scale: True

  optim:
    type: Adam
    lr: 0.003
    betas: [0.9, 0.999]

  sched:
    type: MultiStepLR
    gamma: 0.1
    milestones: [40, 100, 160]

validate:
  batchSize: 1
  numBatches: 4
  width: 960
  height: 720
  
  in_channels: 1
  out_channels: 12 

  augment:
    rotate: False
    scale: True
  datapath: "/home/wipkat/data/pip_val"
